version: '3.8'

services:
  document-processor:
    build: .
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
      - PORT=8080
      - LOG_LEVEL=debug
    env_file:
      - .env
    volumes:
      # Mount source code for development (optional)
      - ./src:/app/src:ro
    depends_on:
      - redis
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
